# Generated by Django 3.1 on 2022-11-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221121_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
